### ISSUE TITLE
朴素贝叶斯部分有段代码可能有Bug

### ISSUE THREAD

**Issue by CaiShee** [lk485/ml#2]
`src\naive_bayes.py` line19-21
```
for k in range(y_categories):
        for i, n in enumerate(x_categories): 
                self.P_cond[k][i] = self.estimate_prob(X[y == k, i], n) 
```
意义不是很明确且可能存在 n 和 self.P_cond[k][i] 向量维度不匹配的情况

**Comment by luokn** [comment]
这里就是计算条件概率`P(X_i = a_{ij} | Y = k)`, `n`是特征类别数量, `estimate_prob`返回值与`self.P_cond[k][i]`的向量维度一致，都是`n`.

**Comment by CaiShee** [comment]
```
self.P_cond = [np.zeros([X.shape[1], n]) for n in x_categories]
    for k in range(y_categories):
        for i, n in enumerate(x_categories):  # 第i个特征有n_i个类别
            self.P_cond[k][i] = self.estimate_prob(X[y == k, i], n)  # 类别为k时，i特征所有取值的概率
```

源码在初始化 P_cond 数组时一共初始化了 x的特征维数个，但在更新矩阵时却一共更新了 y 的类别数量的矩阵，也就是说当 y的类别数大于 x 的维数时会出现数组越界的情况，这似乎不是很合理；

如果 P_cond 数组的第 k 个元素代表的时 P(X_i = a_{ij} | k)，那么P_cond数组的初始化似乎做的不是非常合理，`self.P_cond[k][i] = self.estimate_prob(X[y == k, i], n)`中 P_cond[k][i] 的维度等于 x_categories[k]， 而 estimate_prob(X[y == k, i], n)维度等于n 也即是 x_categories[i]，在更普遍的案例中这两者可能未必相等。

**Comment by luokn** [comment]
多谢指出, 这里的`P_cond`初始化维度有问题, 它的第三个维度不同, 因此不能使用list[ndarray], 有空可以帮忙提PR修改一下，谢谢.
